apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines
  namespace: pov-project
  labels:
    app: airlines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airlines
  template:
    metadata:
      labels:
        app: airlines
    spec:
      containers:
      - name: airlines
        image: pov-sim-airlines:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
