apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: flights
  name: flights
  namespace: pov-project
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flights
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: flights
    spec:
      containers:
        - image: pov-sim-flights:latest
          name: flights
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
