apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: pov-project
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: pov-sim-frontend:latest
          name: frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /app
          #     name: frontend-cm0
          #   - mountPath: /app/node_modules
          #     name: frontend-claim1
      restartPolicy: Always
      volumes:
        # - configMap:
        #     name: frontend-cm0
        #   name: frontend-cm0
        # - name: frontend-claim1
        #   persistentVolumeClaim:
        #     claimName: frontend-claim1
